### ISSUE TITLE
CPL+BOM upload error on JLCPCB

### ISSUE THREAD

**Issue by XenoXXenoX** [eamars/RaspberryPi-Pico-Motor-Expansion-Board#13]
Uploading CPL-pico_expansion_board.csv and BOM-pico_expansion_board.csv on JLCPCB shows error

The below parts won't be assembled due to data missing.
TP_UART1,TP3,TP2,TP5,TP4,DESIGNATOR designators don't exist in the CPL file.

**Comment by eamars** [comment]
Hi @XenoXXenoX Sorry for replying this issue in time. 

This is completely normal. TP* are considered as test points on the board and are not designed to be assembled. You can ignore those errors and proceed.

**Comment by Kasper1986** [comment]
Hi @eamars 
Does this error also apply?
Can i continue with this?
![Screenshot_20240723-061037](https://github.com/user-attachments/assets/edc178e5-233a-4d45-95f1-7f299e2ea3bc)
![Screenshot_20240723-061134](https://github.com/user-attachments/assets/a8a3db81-a75d-454d-89e7-e8a16403f51c)
![Screenshot_20240723-060931](https://github.com/user-attachments/assets/6c153e24-75b0-4539-8eb2-1eda264dd1ad)

**Comment by eamars** [comment]
Test points are removed from the BOM now so the error does not apply anymore. 

From your screenshot I can see the power inductor is missing. I'm not sure what elses are missing. Perhaps you can provide a better screenshot and post on the discord so other may be able to find the substitution.

**Comment by Kasper1986** [comment]
The power inducters is not available, that is why.

I could not see this on my phone, i saw it on my computer

I cannot find a good candidate for a replacement, also i do not have discord yet, but will try to set it up next month.

**Comment by eamars** [comment]
@Kasper1986 BTW I'm working on the V2 PCB. I will provide alternatives for parts that are likely to be out of stock. The new PCB will be released in the next few weeks.
