### ISSUE TITLE
JLCPCB Wrong placement on most parts.

### ISSUE THREAD

**Issue by MrLuckys** [eamars/RaspberryPi-Pico-Motor-Expansion-Board#14]
Hi
It seems like most parts get added to the wrong location and or is rotated incorrectly.
![Screenshot 2024-03-24 182921](https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/assets/38002089/e2365ac5-64bb-40be-b281-a3a496d47218)

And it is not possible to move single parts if 2 of the same type is stacked on top of each other, is this a user error or a changed coordinate system?

**Comment by eamars** [comment]
Hi, @MrLuckys may I ask which file are you using for component placement? I believe the one from https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/tree/main/production has been fixed to match with the component arrangement.

**Comment by MrLuckys** [comment]
@eamars , You are completely right! The new files correct, I've tried to use the old files that I downloaded early last year, and did not delete the repository, and was still using this for some reason!

Issue resolved, user error!
