### ISSUE TITLE
Missing STL Files

### ISSUE THREAD

**Issue by Mojojojo31** [eamars/RaspberryPi-Pico-Motor-Expansion-Board#2]
The STL files for 12864 display mount is missing.
Love Your work.

**Comment by eamars** [comment]
Thank you! 
In fact I'm working on the new mini 12864 mount as I noticed the fly 12864 has slightly different component placement than the biqu one. In this case I will re-design the mounting chassis for the screen.

**Comment by Mojojojo31** [comment]
Which mini 12864 would you recommend to buy?

**Comment by eamars** [comment]
@Mojojojo31 Biqu 12864 could reuse most of the Voron printed parts and mounting chassis. However I only have Fly 12864 on hands so I might priorities on adding Fly support first, then the Biqu one.

**Comment by Mojojojo31** [comment]
Due to my research the fly is in Germany not easy available. I will buy the Biqu mini 12864 and let you know how the version need to be changed.

**Comment by eamars** [comment]
Cool. That also work!
Thanks for having attention to my project ;)
