### ISSUE TITLE
Suggestions on where to have board made?

### ISSUE THREAD

**Issue by ande7824** [eamars/RaspberryPi-Pico-Motor-Expansion-Board#3]
This is a great project! Thank you for sharing. 

This appears to require having a board made to your specifications you've attached.  Do you have suggestions on where to go and how much it costs?

Thank you.

**Comment by eamars** [comment]
Hi @ande7824, Thanks for having interest in this project.
I was using service from https://jlcpcb.com/ for the prototyping. 

For making your board, you could submit the GERBER zip file https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/blob/main/production/GERBER-pico_expansion_board.zip to the jlcpcb to get a quote. The basic board usually costs about $12 for 5 samples. 
![image](https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/assets/973159/722e0198-e7ee-4c57-b451-a6f3c629b125)

If you're not using the PCBA (PCB Assembly service from JLCPCB), You need to buy components yourself. You need to upload the [BOM file](https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/blob/main/production/LCSC_Bom.csv) to https://www.lcsc.com/bom to get a quote. Make sure you will buy enough components and spares then place the order. The total cost of 10 boards is around $60. 

Hope above information will help.

**Comment by ande7824** [comment]
That's perfect! Thank you.

**Comment by eamars** [comment]
Hi @ande7824 
A new instruction has been added here https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/blob/main/production/README.md to help with PCB manufacturing. 

Please join our discord server if you have further questions https://discord.gg/ZhdThA2vrW
