### ISSUE TITLE
Need help with PCB manufacture in JLCPCB

### ISSUE THREAD

**Issue by TQBCPC** [eamars/RaspberryPi-Pico-Motor-Expansion-Board#4]
Hi,

I am trying to have the PCB made in JLCPCB, but in the component placement, I get components wrongly placed. 
What am I doing wrong? Could it be the CPL file?

Thank You for this great project,
Tiago

**Comment by eamars** [comment]
Hi @TQBCPC 
Yes the CPL only provide correct placement (orientation) for some smaller surface mount components. Chips and bigger caps/inductors need to be adjusted accordingly. 

Do you have any idea how to fix this issue?

**Comment by TQBCPC** [comment]
With a lot of trial and error I think I was able to place them.
![capture-2023-07-09T00_58_12 681Z](https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/assets/71200119/f315a55f-43de-46a2-a842-f2c9efff05e5)
[CPL-pico_expansion_board_teste.csv](https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/files/11996482/CPL-pico_expansion_board_teste.csv)
![capture-2023-07-09T00_58_00 699Z](https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/assets/71200119/998e4b1b-9411-464e-b8a9-54092f12a4ca)

But I'm unsure about the L1 Power inductor orientation and the U3 orientation.

**Comment by eamars** [comment]
The power inductor is unipolar. I will check the orientation of U3 tonight
But thank you very much for your help on that! I will seek to merge your change today.

**Comment by eamars** [comment]
Your placement is correct. I've merged your change.
Thanks again for your help!

**Comment by TQBCPC** [comment]
Thank You!
