### ISSUE TITLE
Adding a status RGB LED

### ISSUE THREAD

**Issue by TQBCPC** [eamars/RaspberryPi-Pico-Motor-Expansion-Board#5]
Is there a possibility to add a RGB LED in the shield body assembly, illuminating the powder cup, that lights up **white** while the OpenTrickler is idle or trickling , **green** when trickling stops inside normal range and **red** when trickling stops but overshoots?
Can it be coded into the Raspberry Pico W? And how would it be wired with the expsnsion board?

**Comment by eamars** [comment]
Speaking of the LED: 
* So far the 2x Rotary Button LED on the mini 12864 display is doing what you're asking for. The code supports two states with customized colour that you can select over the web interface.
* I have plan to add few more dedicated 5V PWM output to the board for further expansion for Neopixel LED and Servo motors. 
  - Neopixel LEDs can be daisy chained. I'm planning to add few more to luminate the charge port. 
  - The miniature servo motor can be used to lift up/down the charge tube or open/close the charge port. 

The change is planned for v2.0 for which I'll work on in the near future. 

FYI Annex-Engineering is planning to design something similar except for the on-board RS232 capability. 
![image (3)](https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/assets/973159/9fd819e1-6985-4155-ab8e-96d098244021)

**Comment by TQBCPC** [comment]
Thank You!

**Comment by eamars** [comment]
The requirement duplicates with https://github.com/eamars/RaspberryPi-Pico-Motor-Expansion-Board/issues/9. We will track there.
